### ISSUE TITLE
Versions 0.43 and 0.44 missing

### ISSUE THREAD

**Issue by Strayer** [epitaphmike/react-native-dash#10]
The two most recent versions of react-native are not yet in this docset. Tried running the build script but ran into some problems (probably only my setup).

Maybe it makes sense to use the devdocs.io scraper? They have a pretty decent version of the react native docs (although only on 0.43)

https://github.com/Thibaut/devdocs/blob/master/lib/docs/scrapers/react_native.rb

**Comment by thsig** [comment]
@Strayer: I fixed this on my end (and compiled the docset for 0.44 locally) by removing the `-E` flag, see: https://github.com/epitaphmike/react-native-dash/pull/7#issuecomment-302484707

Hope this helps!

**Comment by epitaphmike** [comment]
Updated
