### ISSUE TITLE
Update to v0.19

### ISSUE THREAD

**Issue by altern8tif** [epitaphmike/react-native-dash#2]
I'm intending to update the Dash docset to v0.19.

Unfortunately, the HTML is not rendering properly (ie. missing images) after running your script.  The images in the docset package contents all seem to be there and well-referenced, so I'm not sure what the issue might be.

![screen shot 2016-01-31 at 10 19 58 pm](https://cloud.githubusercontent.com/assets/5793364/12702602/fd80c008-c868-11e5-9c72-0442cf015150.png)

**Comment by epitaphmike** [comment]
Let me look into this issue. I will be updating the Dash docset today to v0.19

**Comment by epitaphmike** [comment]
@altern8tif It seems as if you are missing the styles for the page. Do you have a link tag in your index.html under [ react-native-dash > Contents > Resources > Documents > react-native > index.html ] ?

The link tag would look like this
`<link rel="stylesheet" href="css/react-native.css">`

Do you have the following css under [ react-native-dash > Contents > Resources > Documents > react-native > css > react-native.css ]?

**Comment by altern8tif** [comment]
Yup both the link tag and the css file are present.

![screen shot 2016-01-31 at 11 36 19 pm](https://cloud.githubusercontent.com/assets/5793364/12703035/8a69ae8a-c873-11e5-9c6f-1c1fa6f63288.png)
![screen shot 2016-01-31 at 11 36 48 pm](https://cloud.githubusercontent.com/assets/5793364/12703036/8a9fa4a4-c873-11e5-8cd4-b08806cd265f.png)

**Comment by epitaphmike** [comment]
It seems your link is pointing to css/react-native.css**.html** and not css/react-native.css

Try removing the .html from the link tag and you should be good.

I also just updated the repo for v0.19.0. If you pull and run ./build.sh from the repo it should build the latest docs.

**Comment by altern8tif** [comment]
Ah! Wonder how I missed that... Thanks!

Will you be making a PR to the [Dash-User-Contributions](https://github.com/Kapeli/Dash-User-Contributions) repo too?

**Comment by epitaphmike** [comment]
As we speak. I will be submitting the PR in a few minutes. @Kapeli is very quick about PR's as well, so hopefully it will be in shortly.

**Comment by altern8tif** [comment]
:+1:

**Comment by epitaphmike** [comment]
PR submitted to https://github.com/Kapeli/Dash-User-Contributions/pulls
