### ISSUE TITLE
Some links redirect to main react native (getting started) webpage

### ISSUE THREAD

**Issue by Amwam** [epitaphmike/react-native-dash#3]
I've found a few links in the latest released version of the docset (0.19.0) where the link would redirect to the getting started page.
A few instances I've found are:

- browsing Text, then selecting the `View#style` link. 
    similarly the `color` link in the same page
- TouchableHighlight selecting `TouchableWithoutFeedback props... `

Also there have been a few releases of react native since 0.19.0, So it would be good to have everything up to date if possible.

**Comment by epitaphmike** [comment]
These are all fixed. The latest version as of this comment 0.24.0 is now updated.
