### ISSUE TITLE
Update for newest release

### ISSUE THREAD

**Issue by afantree** [epitaphmike/react-native-dash#5]
Hey,

Could you update the docs for newest release? The newest version is 0.34, THANKS!

**Comment by zhigang1992** [comment]
[React_Native.docset.zip](https://github.com/epitaphmike/react-native-dash/files/501195/React_Native.docset.zip)

You can try this one before author update it.

**Comment by zhigang1992** [comment]
Had to cp `css/react-native.css` to `css/react-native.css.html`. not exactly sure why but it works.

**Comment by afantree** [comment]
@zhigang1992 Thanks

**Comment by epitaphmike** [comment]
The latest version 0.35 is now available. Thank you for your patience.
