### ISSUE TITLE
Code snippets now showing in Dash

### ISSUE THREAD

**Issue by dbarros** [epitaphmike/react-native-dash#6]
Is it possible to get the React Native docset to show the same code samples that are rendered in the website version? For example, on this [page](https://facebook.github.io/react-native/docs/text.html) you can see a code snippet at the top (in the Text section).

When viewing the page in Dash, it's not there. ![Screenshot](http://i.imgur.com/HjNXZ1D.png)

**Comment by altern8tif** [comment]
The code snippets are written in React (on the official documentation), which makes it a little difficult to render to Dash's docset.  Not sure if there are workarounds though.

**Comment by epitaphmike** [comment]
The code snippets are actually just iframes and not loading because of the url format missing http:.

I have updated the script and the code snippets now render. Version 0.35 is now available. I will be submitting a PR to Dash shortly.
