### ISSUE TITLE
Update to newest release

### ISSUE THREAD

**Issue by altern8tif** [epitaphmike/react-native-dash#8]
Facebook is moving to a [monthly release schedule](https://facebook.github.io/react-native/blog/2017/01/07/monthly-release-cadence.html) so that'll mean less updates to the Dash repo.

In the meantime, would it be possible to update to 0.40 (the December release)?

**Comment by epitaphmike** [comment]
I'll be able to update to 0.40 by tomorrow at the latest.

**Comment by thedaniel** [comment]
Just checking in :) Normally I'd be happy to open a PR myself but I'm rushing off to the airport (hence looking for a RN dash docset)

**Comment by epitaphmike** [comment]
Give me a few minutes to push the changes. Time got away from me. I'll submit the PR in a moment.

**Comment by epitaphmike** [comment]
@thedaniel and @altern8tif A PR has been submitted to the Dash repo
