### ISSUE TITLE
Problem with build.sh

### ISSUE THREAD

**Issue by amestsantim** [epitaphmike/react-native-dash#9]
I tried to build the docset as per the given instructions and it does generate a new docset, the only problem is that some of the links are broken and when you view the docset in view, it looks very bad as it can not find images and the css files.

The reason for this is as I have discovered the -k option in the wget command in the build.sh file.
The -k or --convert-links option of wget converts links in the downloaded files so that they can be found locally but while doing this, it also changes the extensions of some of the files linked to from the html files, it adds an extra .html extension to the images and css links in the head section.
I run the script again without the -k option but that did not work because the link paths were not converted to local.

So, there needs to be some solution for this!

**Comment by thsig** [comment]
@amestsantim: Removing the `-E` flag (keeping other flags as they are) worked for me, so hopefully you can use that tweak to compile the docset for yourself until this is fixed on `master`.

See: https://github.com/epitaphmike/react-native-dash/pull/7#issuecomment-302484707

**Comment by epitaphmike** [comment]
Updated and ran fine. Please pull down the latest changes. Thanks
